---
deployment:
  tasks:
    - /usr/local/bin/php artisan config:clear
    - /usr/local/bin/php artisan view:clear
    - /usr/local/bin/php artisan cache:clear
    - /usr/local/bin/php artisan route:clear
